### ISSUE TITLE
how to install using `jupyter labextension install `

### ISSUE THREAD

**Issue by cocoaaa** [telamonian/theme-darcula#1]
Hi, thank you for working on this theme. 
I'd like to give it a try, but am not sure how I can install this using the usual `jupyter labextension install` command. Could you help?

Thanks!

**Comment by cocoaaa** [comment]
I followed the steps in this repo(https://github.com/youngthejames/jupyterlab_filetree) and got it to work.  Closing the issue.

**Comment by telamonian** [comment]
I agree that the README was somewhat lacking. It now has complete installation instructions.
