### ISSUE TITLE
Scrollbars are not styled in Firefox 70

### ISSUE THREAD

**Issue by timhoffm** [telamonian/theme-darcula#11]
![grafik](https://user-images.githubusercontent.com/2836374/69428522-b5a0e300-0d31-11ea-9cf5-58a6ffe400c5.png)

jupyterlab: 1.2.3
firefox: 70.0

**Comment by telamonian** [comment]
I cannot reproduce your issue on firefox 70:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2263641/69442626-e6c1e900-0d1a-11ea-9db8-f0db4e15424c.png">

Please open your settings editor, click on "Theme", and make sure that the `"theme-scrollbars"` flag is set to `True`

**Comment by timhoffm** [comment]
Yes, indeed. Sorry for the noise. I've made a PR so that hopefully others will not fall into this trap.
