### ISSUE TITLE
This extension does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by mochp** [telamonian/theme-darcula#13]
Extension Installation Error
An error occurred installing @telamonian/theme-darcula.

Error message:

This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.1.3 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.1.3 <2.0.0 @jupyterlab/apputils

**Comment by remziduzagac** [comment]
I really love this extension can you update for new version please

**Comment by telamonian** [comment]
@telamonian/theme-darcula v2.0.0 has now officially been released! v2.0.0 will support all JupyterLab 2.x versions. Please try it out:

```
jupyter labextension install @telamonian/theme-darcula
```

If there are any issues please report them on this bug tracker
