### ISSUE TITLE
nbextension

### ISSUE THREAD

**Issue by bytearchive** [telamonian/theme-darcula#21]
can this be installed as nbextension i.e. in notebook as I do not want to use lab

**Comment by telamonian** [comment]
noooo. no






no

**Comment by telamonian** [comment]
but in seriousness, the codebases for nb classic and jupyterlab are not related at all, and theming is handled totally differently (which is to say, not handled at all in nb classic).

There are existing projects that hack theming into nb classic (like [this](https://github.com/dunovank/jupyter-themes)). You may also be interested in the in-progress [jupyterlab-classic](https://github.com/jtpio/jupyterlab-classic) project, which refactors jupyterlab into something that looks and feels more like the classic notebook (but with the goodness of all the new jlab themes and extensions), though I don't think that's ready for wider use yet.

But the `theme-darcula` theme in this repo is and will remain jlab only

**Comment by bytearchive** [comment]
no worries, i'll try some of the links you mentioned.
the lab keeps hanging on my machine and it seems it is doing too many things on one page and keeps getting frozen

**Comment by telamonian** [comment]
> the lab keeps hanging on my machine and it seems it is doing too many things on one page and keeps getting frozen

well that's not good. We consider freezing to be a major issue, so if you can please submit a bug report to the main jupyterlab issue tracker [here](https://github.com/jupyterlab/jupyterlab/issues). One of our major design goals for jupyterlab is to have overall feature/UX parity with nb classic. So if you're having a significantly worse experience with jupyterlab than with nb classic, that's definitely something we want to hear about
