### ISSUE TITLE
do a new release for jupyterlab 3.x

### ISSUE THREAD

**Issue by telamonian** [telamonian/theme-darcula#22]
This theme has yet to upgrade/do a new release that's compatible with jlab 3.x. I'll track related progress in this issue

**Comment by CarloNicolini** [comment]
Actually, for completeness the error message after trying the installation reads:

	An error occured.
	ValueError: The extension "@telamonian/theme-darcula" does not yet support the current version of JupyterLab.


	Conflicting Dependencies:
	JupyterLab              Extension      Package
	>=3.0.6 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
	>=3.0.5 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/apputils
	See the log file for details:  /tmp/jupyterlab-debug-xwakq6pf.log

**Comment by telamonian** [comment]
This was resolved by #19

@CarloNicolini and anyone else who's interested, you can install the new 3.x release of `@telamonian/theme-darcula` with just

```bash
pip install theme-darcula
```

and thanks to the new extension system shipped in jlab 3, you won't even need to do a `jupyter lab build` afterwards; it just works, no build. Which is awesome
