### ISSUE TITLE
Status bar is missing with latest JupyterLab

### ISSUE THREAD

**Issue by gouku** [telamonian/theme-darcula#42]
![image](https://user-images.githubusercontent.com/9361308/129047127-12ac274a-31a1-4dd7-8ec2-b140bc54c130.png)

But when switched back to built-in themes JupyterLab Light/Dark the status bar will be back.

JupyterLab version: 3.1.4

**Comment by telamonian** [comment]
well it shouldn't do that. I'll look into it
