### ISSUE TITLE
Panels not loading

### ISSUE THREAD

**Issue by nhols** [telamonian/theme-darcula#7]
Love the darcula theme, this looks awesome. Getting issues with some of the panels loading, running jupyter lab 1.0.2 in chrome Version 76.0.3809.132 (Official Build) (64-bit). Any ideas?

![image](https://user-images.githubusercontent.com/54774848/64079390-e64b2080-ccde-11e9-89c2-379bbd945593.png)

**Comment by telamonian** [comment]
Upgrade to Jupyterlab `v1.1.1` if you can. This is probably related to jupyterlab/jupyterlab#7129, and upgrading fixed similar issues for other people.

If you can't upgrade, please try using one of the built-in Jlab themes and then tell me if you still see the issues.

**Comment by nhols** [comment]
Jupyterlab v1.1.1 worked, thankyou!
